### ISSUE TITLE
How to update filter after adjusting a parameter of this filter?

### ISSUE THREAD

**Issue by 3togo** [nicolasbrailo/VlcFreemote#18]
If I change the value of a parameter of one of your filters, say "brightness",  what is the proper way to to reapply this filter so that it will ensure the movie is playing smoothly?

Thank in advance for any suggestion.

**Comment by nicolasbrailo** [comment]
Hi 3togo! I'm not sure I understand your question. Any adjustments made in the app should be automatically applied to the VLC instance you are connected to. Changing a brightness slider should automatically change the image setting (is brightness one of the supported configurations? I don't recall if that's the case).

**Comment by 3togo** [comment]
I got it. It is done through vlc connector. 
Thank you very much

**Comment by nicolasbrailo** [comment]
ohh I see, you're working on a new feature, not asking about how to use the app. Got it now!
If I can help you out with something please let me know. Looking forward to a pull-request!
