### ISSUE TITLE
"Could not connect to VLC... "

### ISSUE THREAD

**Issue by DrNion** [nicolasbrailo/VlcFreemote#19]
The connection isn't possible for some reasons.

I can connect to vlc with other apps or with my browser without any problems.
Even the server with the vlc player has been detected by the  VlcFreemote app. 
But after inserting the PW and clicking on OK a toast message immediately appears saying that it `Could not connect to VLC at <IP>. Please select a new server.` 

My vlc player sits on a RaspberryPi and I tried to connect with several phones. Non of them worked.

**Comment by nicolasbrailo** [comment]
Hi @DrNion! Thanks for the feedback! It's hard to troubleshoot an individual network setup, so I'm afraid there's not a lot of help I can offer. The app will report an active VLC server for anything that has a listening socket at port 8080 in your network. If whatever is listening at that port is not really VLC, the app will just fail. Is it possible that's the case?

If you can connect with your browser, maybe you can try using the url to manually specify the server you want the app to connect to. If that fails, might be worth posting the ADB logs - I believe it should print the server it's trying to connect to, and maybe we can deduce more information from that.
