### ISSUE TITLE
[FR] volume control

### ISSUE THREAD

**Issue by ildar** [nicolasbrailo/VlcFreemote#2]
Is critically missing

**Comment by nicolasbrailo** [comment]
@ildar thanks for the report. Do you mean the ability to control the volume using the media keys / hardware buttons? Yes, that'd be a very good feature to have. It's implementation isn't trivial, so I don't think I'll be able to work on it any time soon. PR's are more than welcome, though.

**Comment by ildar** [comment]
I mean i don't see volume controls, see the screenshot.

**Comment by ildar** [comment]
![Screenshot_20210131-180640](https://user-images.githubusercontent.com/517752/106383857-52f5ad80-63f2-11eb-9bb5-5a627b5a6332.png)

**Comment by nicolasbrailo** [comment]
In the control area (bottom of the screen) there are two sliders, the top
one controls the play time and the bottom one controls the volume. Is the
bottom slider not working for you? The volume slider may work only while
media is playing.

**Comment by ildar** [comment]
eeem, yes, stupid me. I must be blind.
Though it always jumps back to 0. Semi-useful.

**Comment by nicolasbrailo** [comment]
It would certainly be more user friendly if the app "remembered" your setting when VLC isn't playing. The current architecture is fairly stateless, so adding this bit of functionality is possible but not trivial. PR's are welcome, though!
