### ISSUE TITLE
A Display Bug

### ISSUE THREAD

**Issue by franklinbill** [nicolasbrailo/VlcFreemote#24]
Dear developer
In the process of using, I found a bug in layout / display. As shown in the figure, the upper part of the text in the input box of the home page is blocked, which may be an adaptation problem.
App version is 1.10, my mobile phone is Google nexus 6, screen resolution setting is 1440 * 2560, font size is the largest, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
![image](https://user-images.githubusercontent.com/18572115/79224439-a90e5a00-7e8d-11ea-95a4-bd6403ed445c.png)

**Comment by nicolasbrailo** [comment]
Interesting that the "use this" button is off-center, but the "start scanning" button is not. I suspect this is the problem: https://github.com/nicolasbrailo/VlcFreemote/blob/master/app/src/main/res/layout/fragment_server_select_view.xml#L21

Maybe a different height parameter will have a more sane rendering?
Unfortunately, I won't be able to test this change anytime soon. @franklinbill if you're up for a PR I'll be happy to accept it!

Also: Thanks for the bug report! Even if we can't fix it now I'm hoping some day we will.
